dist: xenial
language: php
php:
  - 7.1.3
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y ant
install:
  - composer self-update
  - composer install --prefer-source --no-interaction
before_script:
  - ant unit-testing
script:
  - phpunit --bootstrap vendor/autoload.php tests/
cache:
  directories:
  - vendor
